const products=[{id:1,name:'Karamelli şokolad süýjüsi',category:'candy',emoji:'🍬',weight:'250 g',price:48,badge:'Meşhur',origin:'Demo önüm',description:'Ýumşak karamelli doldurgyçly şokolad süýjüsi. Bu maglumat diňe katalogyň işleýşini görkezmek üçin ulanylýar.'},{id:2,name:'Süýtli şokolad Classic',category:'chocolate',emoji:'🍫',weight:'100 g',price:36,badge:'Täze',origin:'Demo önüm',description:'Süýtli şokolady halaýanlar üçin klassik görnüş. Hakyky öndüriji we düzüm soň doldurylýar.'},{id:3,name:'Wanilli wafli Premium',category:'cookie',emoji:'🧇',weight:'180 g',price:29,badge:'-10%',origin:'Demo önüm',description:'Wanil tagamly ýeňil wafli. Aksiýa we baha maglumatlary diňe görkezme maksatly.'},{id:4,name:'Miwe tagamly marmelad',category:'candy',emoji:'🍭',weight:'300 g',price:42,badge:'Täze',origin:'Demo önüm',description:'Dürli miwe tagamlaryndaky reňkli marmeladlar. Hakyky surat soň ýerleşdiriler.'},{id:5,name:'Gara çaý Royal Blend',category:'tea',emoji:'🫖',weight:'100 g',price:55,badge:'Top',origin:'Demo önüm',description:'Gündelik içmek üçin gara çaý. Gelip çykyşy, düzümi we taýýarlanyş usuly soň görkezilip bilner.'},{id:6,name:'Şokoladly köke Selection',category:'cookie',emoji:'🍪',weight:'240 g',price:39,badge:'Meşhur',origin:'Demo önüm',description:'Şokolad bölejikli köke. Önüm kartasynyň jikme-jik görnüşini görkezýän demo maglumat.'},{id:7,name:'Sowgat gutusy Mini',category:'gift',emoji:'🎁',weight:'8 önüm',price:120,badge:'Sowgat',origin:'Demo toplum',description:'Kiçi sowgat üçin dürli süýjülerden düzülýän toplum. Düzümi müşderiniň býujetine görä saýlanyp bilner.'},{id:8,name:'Ajy şokolad 72%',category:'chocolate',emoji:'🍫',weight:'90 g',price:44,badge:'Premium',origin:'Demo önüm',description:'Kakao tagamy güýçli ajy şokolad. Hakyky kakao göterimi we önüm maglumatlary tassyklanandan soň goýlar.'}];
const state={category:'all',query:'',sort:'default',favorites:new Set(JSON.parse(localStorage.getItem('suyjiler-favorites')||'[]')),cart:JSON.parse(localStorage.getItem('suyjiler-cart')||'[]')};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],productGrid=$('#productGrid'),overlay=$('#overlay'),cartDrawer=$('#cartDrawer'),productModal=$('#productModal'),toast=$('#toast');
function saveState(){localStorage.setItem('suyjiler-cart',JSON.stringify(state.cart));localStorage.setItem('suyjiler-favorites',JSON.stringify([...state.favorites]))}function money(v){return`${v} TMT`}
function filteredProducts(){let list=products.filter(p=>{const c=state.category==='all'||p.category===state.category,t=`${p.name} ${p.origin} ${p.weight}`.toLowerCase();return c&&t.includes(state.query.toLowerCase())});if(state.sort==='low')list.sort((a,b)=>a.price-b.price);if(state.sort==='high')list.sort((a,b)=>b.price-a.price);if(state.sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'tk'));return list}
function productCard(p){return`<article class="product-card"><span class="badge">${p.badge}</span><button class="heart ${state.favorites.has(p.id)?'active':''}" type="button" data-favorite="${p.id}" aria-label="Halanlaryma goş">${state.favorites.has(p.id)?'♥':'♡'}</button><button class="product-image" type="button" data-details="${p.id}" aria-label="${p.name} barada maglumat"><span>${p.emoji}</span></button><div class="product-meta"><span>${p.origin}</span><span>${p.weight}</span></div><h3 data-details="${p.id}">${p.name}</h3><div class="product-bottom"><div class="price"><b>${money(p.price)}</b><small>demo baha</small></div><div class="product-actions"><button class="details-btn" type="button" data-details="${p.id}" aria-label="Jikme-jik maglumat">i</button><button class="add-btn" type="button" data-add="${p.id}" aria-label="Sebede goş">+</button></div></div></article>`}
function bindCards(){$$('[data-add]').forEach(b=>b.addEventListener('click',()=>addToCart(+b.dataset.add)));$$('[data-details]').forEach(b=>b.addEventListener('click',()=>openProduct(+b.dataset.details)));$$('[data-favorite]').forEach(b=>b.addEventListener('click',()=>toggleFavorite(+b.dataset.favorite)))}
function renderProducts(){const list=filteredProducts();productGrid.innerHTML=list.map(productCard).join('');$('#emptyState').style.display=list.length?'none':'block';bindCards()}
function toggleFavorite(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);saveState();renderProducts();showToast(state.favorites.has(id)?'Halanlaryma goşuldy':'Halanlarymdan aýryldy')}
function addToCart(id){const f=state.cart.find(x=>x.id===id);f?f.qty++:state.cart.push({id,qty:1});saveState();renderCart();showToast('Sebede goşuldy')}
function changeQty(id,d){const i=state.cart.find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty<=0)state.cart=state.cart.filter(x=>x.id!==id);saveState();renderCart()}
function removeFromCart(id){state.cart=state.cart.filter(x=>x.id!==id);saveState();renderCart();showToast('Sebetden aýryldy')}
function cartData(){return state.cart.map(i=>({...products.find(p=>p.id===i.id),qty:i.qty})).filter(i=>i.id)}
function renderCart(){const items=cartData(),qty=items.reduce((s,i)=>s+i.qty,0),total=items.reduce((s,i)=>s+i.price*i.qty,0);$('#cartCount').textContent=qty;$('#itemQuantity').textContent=qty;$('#cartTotal').textContent=money(total);$('#cartItems').innerHTML=items.map(i=>`<div class="cart-item"><div class="cart-mini">${i.emoji}</div><div><b>${i.name}</b><small>${money(i.price)} · ${i.weight}</small><div class="qty-controls"><button type="button" data-decrease="${i.id}">−</button><strong>${i.qty}</strong><button type="button" data-increase="${i.id}">+</button></div></div><button class="remove-btn" type="button" data-remove="${i.id}" aria-label="Sebetden aýyr">×</button></div>`).join('');$('#emptyCart').style.display=items.length?'none':'block';$('#cartSummary').style.display=items.length?'block':'none';$('#orderBox').classList.remove('show');$('#copyOrder').classList.remove('show');$$('[data-increase]').forEach(b=>b.addEventListener('click',()=>changeQty(+b.dataset.increase,1)));$$('[data-decrease]').forEach(b=>b.addEventListener('click',()=>changeQty(+b.dataset.decrease,-1)));$$('[data-remove]').forEach(b=>b.addEventListener('click',()=>removeFromCart(+b.dataset.remove)))}
function openCart(){closeModal();cartDrawer.classList.add('open');overlay.classList.add('open');document.body.classList.add('lock');cartDrawer.setAttribute('aria-hidden','false')}
function closeCart(){cartDrawer.classList.remove('open');if(!productModal.classList.contains('open')){overlay.classList.remove('open');document.body.classList.remove('lock')}cartDrawer.setAttribute('aria-hidden','true')}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;closeCart();$('#modalBody').innerHTML=`<div class="modal-image">${p.emoji}</div><div class="modal-copy"><span class="badge-inline">${p.badge}</span><h3>${p.name}</h3><p>${p.description}</p><div class="modal-facts"><div class="fact"><small>Agramy</small><b>${p.weight}</b></div><div class="fact"><small>Görnüşi</small><b>${p.origin}</b></div></div><div class="modal-price"><div><b>${money(p.price)}</b><small style="display:block;color:var(--muted);margin-top:4px">demo baha</small></div><button class="primary" type="button" id="modalAdd">Sebede goş</button></div></div>`;$('#modalAdd').addEventListener('click',()=>{addToCart(p.id);closeModal();openCart()});productModal.classList.add('open');overlay.classList.add('open');document.body.classList.add('lock');productModal.setAttribute('aria-hidden','false')}
function closeModal(){productModal.classList.remove('open');if(!cartDrawer.classList.contains('open')){overlay.classList.remove('open');document.body.classList.remove('lock')}productModal.setAttribute('aria-hidden','true')}
function createOrderText(){const items=cartData(),total=items.reduce((s,i)=>s+i.price*i.qty,0),lines=items.map((i,n)=>`${n+1}. ${i.name} — ${i.qty} sany × ${money(i.price)}`),text=`Salam! Men şu önümleri sargyt etmek isleýärin:\n\n${lines.join('\n')}\n\nJemi: ${money(total)}\n\nAdym: ____\nTelefon: ____\nBellik: Bahalar demo hökmünde görkezildi.`;$('#orderBox').textContent=text;$('#orderBox').classList.add('show');$('#copyOrder').classList.add('show')}
async function copyOrder(){try{await navigator.clipboard.writeText($('#orderBox').textContent);showToast('Sargyt teksti göçürildi')}catch{showToast('Teksti el bilen belläp göçüriň')}}
function showToast(m){toast.textContent=m;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),1500)}
$$('[data-category]').forEach(b=>b.addEventListener('click',()=>{$$('[data-category]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.category=b.dataset.category;renderProducts();$('#catalog').scrollIntoView({behavior:'smooth'})}));$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;renderProducts()});$('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;renderProducts()});$('#openCart').addEventListener('click',openCart);$('#heroOrder').addEventListener('click',openCart);$('#promoOrder').addEventListener('click',()=>$('#catalog').scrollIntoView({behavior:'smooth'}));$('#closeCart').addEventListener('click',closeCart);$('#closeModal').addEventListener('click',closeModal);overlay.addEventListener('click',()=>{closeCart();closeModal()});$('#makeOrder').addEventListener('click',createOrderText);$('#copyOrder').addEventListener('click',copyOrder);$('#clearCart').addEventListener('click',()=>{state.cart=[];saveState();renderCart();showToast('Sebet arassalandy')});$('#favoritesButton').addEventListener('click',()=>{if(!state.favorites.size){showToast('Halan önümleriňiz ýok');return}productGrid.innerHTML=products.filter(p=>state.favorites.has(p.id)).map(productCard).join('');bindCards();$('#emptyState').style.display='none';$('#catalog').scrollIntoView({behavior:'smooth'});showToast('Halan önümleriňiz görkezildi')});$('#menuButton').addEventListener('click',()=>$('#mobilePanel').classList.toggle('open'));$$('#mobilePanel a').forEach(a=>a.addEventListener('click',()=>$('#mobilePanel').classList.remove('open')));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();closeModal()}});renderProducts();renderCart();